version: 0.2

env:
  variables:
    PROJECT: deploytest
    DOTNET_FRAMEWORK: 4.6.1
phases:
  build:
    commands:
      - nuget restore
      - 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe' $env:PROJECT.csproj /p:TargetFrameworkVersion=v$env:DOTNET_FRAMEWORK /p:Configuration=Release /p:DeployIisAppPath="hoa.srca.net" /p:PackageAsSingleFile=false /p:OutDir=C:\codebuild\artifacts\ /t:Package
